# Generated by Django 4.2.5 on 2023-10-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_reciepe_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciepe_model',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reciepe_model',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
