# Generated by Django 4.2.5 on 2023-10-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_reciepe_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciepe_model',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
