# Generated by Django 4.2.5 on 2023-10-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_urlhitcount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reciepe_model',
            options={'ordering': ['name']},
        ),
    ]
